inherit_from: .rubocop_base.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - '.gems/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'
    - '**/*.rake'

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/config_obsoletion.rb

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/HashAlignment:
  EnforcedColonStyle: table

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*.rb'

Rails/HasAndBelongsToMany:
  Enabled: false # Not necessary with mongoid
